version: '3.2'
services:
 mkdocs:
   image: 'ctoland/mkdocs:1.0.4'
   container_name: local-mkdocs
   working_dir: /mkdocs
   ports:
     - "8001:8000"
   volumes:
       # Bind mount
     - type : bind
       source: .
       target: /mkdocs
   command: ["/bin/sh", "deploy-site.sh"]
