defaults: &defaults
  docker:
    - image: ctoland/circleci-build-mkdocs:1.0.4

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mkdocs build --clean
      - run: mkdir /tmp/mkdocs && cp -R site /tmp/mkdocs
      - persist_to_workspace:
          root: /tmp/mkdocs
          paths:
            - site

  deploy_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/mkdocs
      - deploy:
          command: netlify deploy --dir=/tmp/mkdocs/site

  deploy_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/mkdocs
      - deploy:
          command: netlify deploy --prod --dir=/tmp/mkdocs/site

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy_test:
          requires:
            - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
